# Generated by Django 3.1.3 on 2020-11-16 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowsay_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cowtext',
            name='text',
            field=models.CharField(max_length=200),
        ),
    ]
